What is NumPy?

NumPy (Numerical Python) is a core Python library for scientific computing. It provides support for large, multi-dimensional arrays and matrices, plus a wide range of mathematical functions to operate on them.


Why NumPy?

Faster than regular Python lists
More memory-efficient
Powerful built-in mathematical operations
The foundation that data science and machine learning libraries (Pandas, scikit-learn, PyTorch, etc.) are built on top of

In [2]:
# Importing numpy
import numpy as np

### Creating Numpy Arrays

In [2]:
# Basic Array Creation  

# Creating arrays from lists
list_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("List to Array:", list_array)

# Creating multi-dimensional arrays
matrix_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [9, 8, 2]])
print("2D Array:\n", matrix_array)

List to Array: [1 2 3 4 5 6 7 8]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 2]]


* Array Generation Functions

In [ ]:

# Generate arrays with specific patterns

zeros_array = np.zeros((6, 4))   # 6x4 array of zeros
ones_array = np.ones((6, 3))     # 6x3 array of ones
basic_array_arange = np.arange(10)
range_array = np.arange(0, 10, 2)   # Array from 0 to 10 with step 2
linspace_array = np.linspace(0, 1, 5)   # 5 evenly spaced points between 0 and 1

print("Zeros Array:\n", zeros_array)
print('\n')
print("Ones Array:\n", ones_array)
print('\n')
print("Basic Array arange:", basic_array_arange)
print('\n')
print("Range Array:", range_array)
print('\n')
print("Linspace Array:", linspace_array)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Basic Array arange: [0 1 2 3 4 5 6 7 8 9]


Range Array: [0 2 4 6 8]


Linspace Array: [0.   0.25 0.5  0.75 1.  ]


### Array Atrributes and Indexing

* Array Attributes

In [ ]:

# Exploring Array Attributes

example_array = np.array([[1, 2, 3], [4, 5, 6], [3, 4, 7]])

print("Shape:", example_array.shape)              # (rows, columns)
print("Dimension:", example_array.ndim)           # number of dimensions
print("Data Type:", example_array.dtype)          # type of numbers stored
print("Total Elements:", example_array.size)      # total count of elements

Shape: (3, 3)
Dimension: 2
Data Type: int64
Total Elements: 9


* Array Indexing and Slicing

In [10]:
# Basic indexing
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("First row:", array_2d[1])

print("Specific element:", array_2d[1, 1])

# Slicing
print("First two rows, first two columns:\n", array_2d[:2, :2])
print("First three rows, first two columns:\n", array_2d[:3, :2])

First row: [4 5 6]
Specific element: 5
First two rows, first two columns:
 [[1 2]
 [4 5]]
First three rows, first two columns:
 [[1 2]
 [4 5]
 [7 8]]


### Mathematical Operations

* Element-wise Opearations

In [ ]:
# Element-wise arithmetic operations

a = np.array([1, 4, 3])
b = np.array([4, 5, 6])

Addition = a + b           # Element-wise addition
Subtraction = a - b        # Element-wise subtraction
Multiplication = a * b     # Element-wise multiplication
Division = a / b           # Element-wise division
Exponentiation = np.exp(a) # e^element,  e^1,  e^4, e^3,  e = 2.718281828459045
Square_root = np.sqrt(a)   # Square root of each element

print("Array a:", a)
print("Array b:", b)
print("a + b:", Addition)
print("a - b:", Subtraction)
print("a * b:", Multiplication)
print("a / b:", Division)
print("e^a:", Exponentiation)
print("Square root of a:", Square_root)

Array a: [1 4 3]
Array b: [4 5 6]
a + b: [5 9 9]
a - b: [-3 -1 -3]
a * b: [ 4 20 18]
a / b: [0.25 0.8  0.5 ]
e^a: [ 2.71828183 54.59815003 20.08553692]
Square root of a: [1.         2.         1.73205081]


* Aggregate Functions

In [ ]:
# Statistical operations
data_array = np.array([11, 2, 7, 4, 5])
data_array2= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Data Array:", data_array)
print("Sum:", np.sum(data_array))      # Sum of all elements
print("Mean:", np.mean(data_array))      # Mean of the elements
print("Median:", np.median(data_array))      # Median of the elements
print("Standard Deviation:", np.std(data_array))      # Standard deviation of the elements
print("Variance:", np.var(data_array))      # Variance of the elements
print("Max:", np.max(data_array))      # Maximum value in the array
print("Min:", np.min(data_array))      # Minimum value in the array

print('\n')

print("Data Array 2:", data_array2)
print("Sum:", np.sum(data_array2))      # Sum of all elements
print("Mean:", np.mean(data_array2))      # Mean of the elements    
print("Median:", np.median(data_array2))      # Median of the elements
print("Standard Deviation:", np.std(data_array2))      # Standard deviation of the elements
print("Variance:", np.var(data_array2))      # Variance of the elements
print("Max:", np.max(data_array2))      # Maximum value in the array
print("Min:", np.min(data_array2))      # Minimum value in the array

print('\n')

print("Sum along axis 0 (columns) for each column in data_array2:", np.sum(data_array2, axis=0))      # Sum along each columns in data_array2
print("Sum along axis 1 (rows) for each row in data_array2:", np.sum(data_array2, axis=1))      # Sum along each rows in data_array2


Data Array: [11  2  7  4  5]
Sum: 29
Mean: 5.8
Median: 5.0
Standard Deviation: 3.0594117081556713
Variance: 9.360000000000001
Max: 11
Min: 2


Data Array 2: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum: 45
Mean: 5.0
Median: 5.0
Standard Deviation: 2.581988897471611
Variance: 6.666666666666667
Max: 9
Min: 1
Sum along axis 0 (columns): [12 15 18]
Sum along axis 1 (rows): [ 6 15 24]


### Advanced Operations

* Reshaping and Transposing

In [ ]:
# Reshaping Arrays
Original_array = np.arange(10) 
Reshaped_array = Original_array.reshape(2, 5)  # Reshape to 2 rows and 5 columns

print('Original Array:', Original_array)
print('shape of Original Array:', Original_array.shape)  # Output: (10,)
print('Reshaped Array:\n', Reshaped_array)
print('Shape of Reshaped Array:', Reshaped_array.shape)  # Output: (2, 5)
print('Transposed of the Reshaped Array:\n', Reshaped_array.T)  # Transpose of the reshaped array  

Original Array: [0 1 2 3 4 5 6 7 8 9]
shape of Original Array: (10,)
Reshaped Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Shape of Reshaped Array: (2, 5)
Transposed of the Reshaped Array:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
