In [2]:
# Importing necessary libraries
import numpy as np
import numpy.linalg as la

In [3]:
# A vector (1D array)
v = np.array([1, 2, 3])
print(v)
print(v.shape) 

[1 2 3]
(3,)


In [4]:
# A matrix (2D array)
M = np.array([[1, 2], [3, 4]])
print(M)
print(M.shape)   # (2, 2) means 2 rows, 2 columns

[[1 2]
 [3 4]]
(2, 2)


Matrix Creation and Basic Operations

In [5]:
# Create Matrices
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

B = np.array([[9,8,7],
             [6,5,4],
             [3,2,1]])

print("Matrix A:\n", A)   # or print(f'matrix A is \n{A}')
print("Matrix B:\n", B)   # or print(f'matrix B is \n{B}')




Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [6]:
# Matrix Addition and subtraction
print("Matrix Addition (A + B):\n", A + B)
print("\nMatrix Subtraction (A - B):\n", A - B)

# Scalar multiplication
print("\nScalar Multiplication (2 * A):\n", 2 * A)

# Element-wise multiplication (NOT matrix multiplication!)
print("\nElement-wise Multiplication (A * B):\n", A * B)

# Matrix multiplication (row × column, dot product style)
print("Matrix Multiplication (A @ B):\n", A @ B)

# Same thing, alternative syntax
print("\nMatrix Multiplication using matmul (A @ B):\n", np.matmul(A, B))

Matrix Addition (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Subtraction (A - B):
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Scalar Multiplication (2 * A):
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Element-wise Multiplication (A * B):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Multiplication (A @ B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix Multiplication using matmul (A @ B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Matrix Properties and Transformations

In [ ]:
# Transpose - flips rows and columns
print("Matrix A Transpose:\n", A.T)

# Transpose — flips rows and columns
Transpose_of_A = A.T
print("\nTranspose of A:\n", Transpose_of_A)

# Diagonal elements of A 
print("\nDiagonal of A:", np.diag(A))

# Diagonal elements of A 
Diagonal_of_A = np.diag(A)
print("\nDiagonal of A:", Diagonal_of_A)

# Create a NEW diagonal matrix (unrelated to A, just demonstrating the function)
diag_matrix = np.diag([1, 2, 3])  
print("\nDiagonal Matrix:\n", diag_matrix)


Matrix A Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Diagonal of A: [1 5 9]

Diagonal of A: [1 5 9]

Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

Determinant of A: 0.0


Linear Algebra Operations

In [ ]:
# Determinant of a Matrix
Determinant_of_A = la.det(A)  # np.linalg.det(A)
print("\nDeterminant of A:", Determinant_of_A)

# Inverse of a Matrix

if Determinant_of_A == 0:
    print("Matrix A is singular (determinant is 0), so it does not have an inverse.")
else:
    Inverse_of_A = la.inv(A) # or np.linalg.inv(A)
    print("\nInverse of A:\n", Inverse_of_A)

    # Check the inverse
    print("\nCheck Inverse (A @ A_inv):\n", A @ Inverse_of_A)
    print("Matrix A is invertible")




Determinant of A: 0.0
Matrix A is singular (determinant is 0), so it does not have an inverse.


Note:
Singular Matrix
A singular matrix is a matrix that does not have an inverse.
Its determinant is 0.


Invertible Matrix
An invertible matrix is a matrix that has an inverse.
Its determinant is not 0.

In [21]:
g = np.array([[4, 2], [3, 4]])
# Determinant of g  
Determinant_of_g = la.det(g)
print("\nDeterminant of g:", Determinant_of_g)

#inverse of g
if Determinant_of_g == 0:
    print("Matrix g is singular (determinant is 0), so it does not have an inverse.")   
else:
    Inverse_of_g = la.inv(g)
    print("\nInverse of g:\n", Inverse_of_g)

    # Check the inverse
    print("\nCheck Inverse (g @ g_inv) should give identity matrix:\n", g @ Inverse_of_g)
    print("Matrix g is invertible")


Determinant of g: 10.000000000000002

Inverse of g:
 [[ 0.4 -0.2]
 [-0.3  0.4]]

Check Inverse (g @ g_inv) should give identity matrix:
 [[1. 0.]
 [0. 1.]]
Matrix g is invertible


In [24]:
# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = la.eig(A)
print("\nEigenvalues of A:", eigenvalues)
print("\nEigenvectors of A:\n", eigenvectors)


Eigenvalues of A: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

Eigenvectors of A:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


Solving Linear Equations

Solve the system of linear equations:

. 2x + y = 5

. x + 3y = 7

In [17]:
# coefficients of matrix
coefficients = np.array([[2, 1],
                         [1, 3]])

# constants
constants = np.array([5, 7])

# solving linear equations 
solution = la.solve(coefficients, constants)
print("\nSolution (x, y):", solution)


# verify the solution
print("\nverification:")
print("2x + 1y =", 2*solution[0] + 1*solution[1])
print("1x + 3y =", 1*solution[0] + 3*solution[1])






Solution (x, y): [1.6 1.8]

verification:
2x + 1y = 5.0
1x + 3y = 7.0


### Question on System of Linear Equations

A party planning company offers three event packages, each combining decorations, food, and equipment in different amounts.

* Package A uses 5 units of decorations, 10 units of food, and 2 units of equipment, for a total cost of $450.

* Package B uses 3 units of decorations, 4 units of food, and 1 unit of equipment, for a total cost of $200.

* Package C uses 2 units of decorations, 3 units of food, and 3 units of equipment, for a total cost of $210.

Find the cost per unit of decorations (x), food (y), and equipment (z).

In [18]:
# SOLUTION TO THE ABOVE QUESTION
import numpy as np
import numpy.linalg as la

# let decorations = x, food = y, equipment = z


# Define the coefficient matrix A and constant vector b
coefficients = np.array([[5, 10, 2],
              [3, 4, 1],
              [2, 3, 3]])
constants = np.array([450, 200, 210])

# Solve the system
solution = la.solve(coefficients, constants)

# Print the solution
print("Solution:", solution)


print("Cost per unit of decorations (x): $", round(solution[0], 2))
print("Cost per unit of food (y): $", round(solution[1], 2))
print("Cost per unit of equipment (z): $", round(solution[2], 2))
print("\n")
# Verify the solution
verification = np.dot(coefficients, solution)
print("Verification:", verification)

Solution: [14.34782609 32.17391304 28.26086957]
Cost per unit of decorations (x): $ 14.35
Cost per unit of food (y): $ 32.17
Cost per unit of equipment (z): $ 28.26


Verification: [450. 200. 210.]


### Problem Definition.

Solve the System of linear equations.

* 3x+2y+z=10.

* x+4y+2z=15.

* x+y+z=8

In [ ]:
# SOLUTION TO THE ABOVE PROBLEM

import numpy as np
import numpy.linalg as la

coefficients = np.array([[3, 2, 1], 
                         [1, 4, 2],
                         [1, 1, 1]])
constants = np.array([10, 15, 8])

solution = la.solve(coefficients, constants)
print("Solution:", solution)
print("x =", solution [0])
print("y =", solution [1])
print("z =", solution [2])

Solution: [1. 0. 7.]
x = 1.0
y = 0.0
z = 7.0


Singular Value Decomposition (SVD)

In [ ]:
# perform Singular Value Decomposition (SVD)
U, S, VT = la.svd(A)

print("\nU (Left singlar vectors):\n", U)
print("\nS (Singular values):\n", S)
print("\nVT Transpose (Right singular vectors):\n", VT)


U(Left singlar vectors):
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

S(Singular values):
 [1.68481034e+01 1.06836951e+00 4.41842475e-16]

VT Transpose (Right singular vectors):
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
